title: Marine Plastic Explorer
baseurl: ''
siteurl: 'https://plasticnavigator.wwf.de'
permalink: /:categories/:title
markdown: kramdown
languages: &languages
  - name: 'English'
    value: 'en'
  - name: 'German'
    value: 'de'
exclude:
  - app
  - internals
  - server
prose:
  media: "assets/uploads"
  rooturl: '_posts'
  siteurl: 'https://plasticnavigator.wwf.de/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: "/"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/layers:
      - name: "layout"
        field:
          element: "hidden"
          value: "layer"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: "/"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "image_file_name"
        field:
          element: "text"
          label: "Image file name (located in assets/uploads/ folder)"
          value: ""
      - name: "image_caption"
        field:
          element: "text"
          label: "Image caption"
          value: ""
      - name: "fact_lead"
        field:
          element: "textarea"
          label: "Optional fact or lead paragraph"
          value: ""
